repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.9.26
  hooks:
    - id: uv-lock
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: fix-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
      exclude: '\.py$'  # This regex excludes all Python files
    - id: check-json
    - id: check-xml
    - id: check-yaml
      name: Check MkDocs.yml in unsafe mode
      files: ^mkdocs\.yml$
      args: ['--unsafe']
    - id: check-yaml
      name: Check all other YAML files in safe mode
      files: \.ya?ml$
      exclude: ^mkdocs\.yml$
    - id: debug-statements
    - id: end-of-file-fixer
      exclude: ^docs/
    - id: pretty-format-json
      exclude: ^notebooks/
      args: ['--autofix', '--indent', '4']
    - id: trailing-whitespace
      exclude: ^docs/
        # Make sure windows user don't push CRLF terminated files
        # More doc about it: https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/
    - id: mixed-line-ending
      args: ['--fix=lf']
      exclude: ^docs/
    - id: detect-private-key
# FIXME I think it would be better to use the mypy precommit hook, to not rely on uv. But I didn't manage to use the venv when using the mypy hook.
- repo: local
  hooks:
    - id: mypy-python-backend
      name: mypy
      entry: uv --project backend run mypy --config-file=backend/pyproject.toml .
      args: []
      language: system
      types: [python]
      pass_filenames: false
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
    - id: nbstripout
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.0
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.6
  hooks:
    - id: bandit
      # Exclude tests bc they contain assert statements, that raise bandit errors
      exclude: tests/
