[project]
name = "docs"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "click<8.3.0",
    "mkdocs-gen-files>=0.6.0",
    "mkdocs-literate-nav>=0.6.2",
    "mkdocs-material>=9.7.1",
    "mkdocs-section-index>=0.3.10",
    "mkdocstrings[python]>=1.0.3",
    "ruff>=0.15.0",
]
