name: Publish-mkdocs-on-github
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘¾ Clone repo to runner
        uses: actions/checkout@v6

      - name: ğŸ Install python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: ğŸ“˜ Install mkdocs dependencies
        working-directory: docs
        run: pip install .

      - name: ğŸš€ Build and deploy updated documentation to gh-pages branch
        working-directory: docs
        run: mkdocs gh-deploy --force
